### ISSUE TITLE
Is hound reading my eslint file?

### ISSUE THREAD

**Issue by kapso** [houndci/hound#1687] opened 2019-03-22 19:14 UTC
Why am I getting these...

- `Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`
- `Missing trailing comma comma-dangle`

...even though I have `.eslintrc.json`

```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "comma-dangle": ["error", "never"]
}
```

...and my `.hound.yml`
```yml
eslint:
  enabled: true
  config_file: .eslintrc.json

ruby:
  config_file: .rubocop.yml

scss:
  enabled: false
```

**Comment by gylaz** [comment] 2019-03-22 19:53
At first glance, shouldn't your `comma-dangle` rule be inside of a `rules` attribute, like:
```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "comma-dangle": ["error", "never"]
  }
}
```
Do you have a PR where you've reproduces this? It would be easier to debug.

**Comment by kapso** [comment] 2019-03-22 21:46
@gylaz thanks yea fixed the `"rules"` part. However still seeing the same issues.

Yea you should see PR `#240` against my account. Not sure if you need the name of the branch?

new `.eslintrc.json`
```json
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "rules": {
    "comma-dangle": ["error", "never"]
  }
}
```

**Comment by gylaz** [comment] 2019-03-23 17:24
I'm not seeing a `Parsing errors` in your latest builds. Are you certain this isn't an older message that Hound made? Since this is a private repo let's move the conversation to the Help widget on our site, this way I can ask to share more.

**Comment by gylaz** [comment] 2019-03-25 21:58
Going to close this, since we're chatting via help.

**Closed by gylaz** 2019-03-25 21:58 UTC
