### ISSUE TITLE
Resolved issues are not being closed when fixed

### ISSUE THREAD

**Issue by jonathansimmons** [houndci/hound#1203] opened 2016-09-15 14:13 UTC
Prior to Github's release announcements yesterday if we resolved an issue Hound caught with a new commit, it would be closed in an outdated diff. That doesn't appear to be happening anymore. 

Is this something within the Hound Team's control?

**Comment by thorncp** [comment] 2016-09-15 15:29
This is not something we have control over. It's a bummer and we're thinking through ways to deal with it.

For now, if the comments are too noisy I think the best course of action is to delete them via the GitHub UI.

**Comment by jonathansimmons** [comment] 2016-09-15 15:49
That is what I thought. One of our dev's noticed that it looks as if the hound comments are being applied to revisions instead of the actual file now. Hence the lack of "outdated diff" functionality.

Thanks for the info, we'll work around it. Let us know if you have any questions or want input on possible solutions.

**Comment by zbeat** [comment] 2016-09-15 15:56
+1 😞

**Comment by blackjid** [comment] 2016-09-15 16:05
maybe use the strikethrough style `~~outdated diff comment~~` on the hound comment, instead of delete them

~~outdated diff comment~~

**Comment by jonathansimmons** [comment] 2016-09-15 16:49
Looking at this further is seems that maybe GitHub has moved away from this on the whole. I don't even see it happening on our own direct comments.

**Comment by gylaz** [comment] 2016-09-15 16:57
This is something that went away completely with the latest GitHub PR reviews. I've reached out to their customer support and they said that they are aware of this, and are looking into ways of solving it. I didn't get a good sense whether this was a regression, or a design decision.

**Comment by treznick** [comment] 2016-09-15 17:26
On the one hand, comments fixed by changes to the diff were hidden from the feed, which was nice. On the other hand though, comments on an outdated diff that were not fixed were also hidden, which sometimes meant sifting through all the closed comments to find the violation. 

I don't want to turn this thread into a feature suggestion forum, but having a UX separate from the github comment feed to see style offenses might be a worthwhile thing. 

But yeah, I empathize with this being outside of your control, and I imagine that being frustrating

**Comment by blackjid** [comment] 2016-09-15 19:16
mmm, I really like there is no need of a separate UI. Is super straight forward to check the violations right inside the PR.

I would love to have a UI for extra thinks... like team stats but nothing really important

**Comment by ddollar** [comment] 2016-09-15 20:40
This definitely makes Hound a lot less useful for my team. The extra comments are really noisy and deleting them by hand just isn't a great long-term solution.

Hopefully Github addresses this on their end. Alternatively could we get Hound to create an actual "code review" session with comments linked together by the same? If you go this route please have Hound submit reviews as either Comment or Requested Changes but not Approved since Github has hardcoded success as a single approver for now.

**Comment by gylaz** [comment] 2016-09-16 16:18
We've created an Idea card on the new Project board: https://github.com/houndci/hound/projects/1#card-114718

**Comment by gerrywastaken** [comment] 2016-09-19 06:01
Pretty amazed Github doesn't work with commonly used integrators before releasing such a significant change. Seems kinda unprofessional.

**Comment by huoxito** [comment] 2016-09-26 20:00
we're having the same problem too, sounds like it would resolve the issue if every houndci feedback were added as a single comment rather than a review, I still see single comments turning into outdated diffs whenever the line is updated, while reviews stay there forever.

**Comment by gylaz** [comment] 2016-09-30 20:19
Here's a PR that attempts to solve this: #1214

**Comment by gylaz** [comment] 2016-10-07 21:02
Hound should now be deleting resolved comments (via #1214). Please do report any issues you may be seeing in regards to this. I'm going to close this as resolved.

**Closed by gylaz** 2016-10-07 21:02 UTC
