### ISSUE TITLE
"Hound encountered an error" with nested/inherited rubocop config

### ISSUE THREAD

**Issue by rahim** [houndci/hound#1146] opened 2016-06-01 12:01 UTC
See https://github.com/teoljungberg/houndradish/pull/64 for a minimal example of this.

I believe this is due to the tree of `inherit_from`s, but that's not confirmed

```
# .rubocop
inherit_from:
- .rubocop/default.yml
```

```
# .rubocop/default.yml
inherit_from:
- enabled.yml
- disabled.yml
```

The problem I was originally trying to solve was inconsistencies between Hound and local Rubocop and being able to continually maintain our Rubocop rules to ensure they're compatible with the version being used by Hound.

To achieve this I'm using the Rubocop version specified in Hound's `Gemfile.lock` locally (currently 0.39.0), https://github.com/houndci/hound/blob/master/Gemfile.lock#L283

My plan had been: each time Hound bumps its Rubocop version, I'd bump our local version to match and also replace our `/.rubocop` folder with the default config corresponding to that Rubocop version (eg https://github.com/bbatsov/rubocop/tree/v0.39.0/config), maintaining only our overrides in `/.rubocop`

This all behaves locally, however Hound returns a check failure, with the catch all "Hound encountered an error" message.

**Comment by jcmorrow** [comment] 2016-06-01 19:39
Thanks for the report Rahim! I've reproduced your issue and am investigating now. I'll update this issue when I have something helpful.

**Comment by jcmorrow** [comment] 2016-06-01 21:07
@rahim there are two things at work here: 

1.  hound is attempting to call

        RuboCop::ConfigLoader.merge(normalized_hound_config, normalized_overrides)

in `app/services/ruby_config_builder.rb` and getting a `TypeError`.

1. It's rescuing from that error by returning a `Hash` when a `RuboCop::Config` is expected.

 The second issue is an easy fix (https://github.com/houndci/hound/pull/1147) but I'm still digging into what the TypeError was and what caused it.

**Comment by rahim** [comment] 2016-06-02 13:17
Thanks for the quick response and investigation @jcmorrow

**Comment by jcmorrow** [comment] 2016-06-02 16:18
@rahim Happy to help! I've also tracked down what's going on with the loading of rubocop configs, it looks like we only follow `inherit_from` once. I've fixed that in an unfinished PR (https://github.com/houndci/hound/pull/1148), but I need to combine it with a couple of other changes (allowing relative filenames in inherit from) in order to make it useful.

**Comment by jcmorrow** [comment] 2016-06-07 20:40
@rahim Just wanted to give you a quick update on this: 

1. I'm pretty sure that now if you run with this config and hound fails to follow the nested `inerit_from`'s it will just run hound with the default config.
1. There's more complexity than I had hoped in parsing these nested configs, so it's probably best if you just don't use that setup for right now (if that's possible). I do want to come up with a solution for it, but we've got some other big moving pieces right now and I'm not sure when I'll get around to finishing up https://github.com/houndci/hound/pull/1147.

**Comment by rahim** [comment] 2016-06-08 18:34
Thanks for the update @jcmorrow.

I believe you're right in that Hound is no longer marking as a failure, but we're seeing warnings inconsistent with the ruleset specified.

We haven't yet decided what we'll do in the interim, perhaps just detach Hound temporarily and rely on local Rubocop for a spell.

Apologies that I've not been able to contribute - I'm mown out at the moment or I'd have offered to take a look at completing the work on your branch (though debatable how effective I'd be!)

**Comment by jcmorrow** [comment] 2016-06-08 18:49
@rahim yeah, I'm pretty sure you're running with the hound defaults now, since it can't parse the config 😢 . I'm not sure if the PR I have is even the right approach to take, so don't worry about contributing there!

**Comment by gylaz** [comment] 2017-09-14 23:29
This one is a year old, so I'm going to close this. Feel free to comment if this issue is still a thing.

**Closed by gylaz** 2017-09-14 23:29 UTC
